planner_server:
  ros__parameters:
    # Note: expected_planner_frequency = 1/max_planning_time, otherwise a warning will be displayed each time the planner takes more time than 1/expected_planner_frequency seconds to generate a path
    expected_planner_frequency: 0.125
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_theta_star_planner/ThetaStarPlanner"
      how_many_corners: 8
      w_euc_cost: 1.0
      w_traversal_cost: 2.0
      w_heuristic_cost: 1.0

      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-10
        do_refinement: true
        refinement_num: 2
        refinement_num: 2